### ISSUE TITLE
1.8.4: Regression: ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by joscha** [FezVrasta/popper.js#238]
In 1.8.4 the IE10 detection was changed from lazy (within the `getBoundingClientRect` method) to eager (in the global scope):

https://github.com/FezVrasta/popper.js/commit/d185897814c2b44e55a53d59d5cd9653018fe4fe#diff-948f8780a0b0051f85e85abd0b5337c4R7

The problem with that is, that parts of our app runs in a node context - and due to popper doing the check eagerly (see https://github.com/FezVrasta/popper.js/commit/d185897814c2b44e55a53d59d5cd9653018fe4fe#diff-948f8780a0b0051f85e85abd0b5337c4R7) this now fails in the node context with:

```
/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:31292
  return navigator.appVersion.indexOf('MSIE 10') !== -1;
         ^
 
ReferenceError: navigator is not defined
    at runIsIE10 (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:31292:10)
    at Object../node_modules/popper.js/dist/esm/popper.js (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:31295:16)
    at __webpack_require__ (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:20:30)
    at Object../src/ui/pin/pin.tsx (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:68362:14)
    at __webpack_require__ (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:20:30)
    at Object../src/ui/flyout/flyout.tsx (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:65476:13)
    at __webpack_require__ (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:20:30)
    at Object.<anonymous> (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:65533:16)
    at Object../src/ui/flyout/stories/flyout.stories.tsx (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:65546:30)
    at __webpack_require__ (/var/lib/buildkite-agent/builds/canva-org/canva-web-build/web/target/build/stories/stories.js:20:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

can we move the IE10 detection back into the method where it is actually used, so it will only be executed if a `Popper` instance is actually constructed? Opened #240.

**Comment by chompomonim** [comment]
+1

Because of same issue had to move back to `1.5.2`.

**Comment by odobdober** [comment]
ReferenceError: navigator is not defined
at eval (webpack:///./node_modules/popper.js/dist/esm/popper.js?:31:20)
at Module../node_modules/popper.js/dist/esm/popper.js (angular-universal-starter/prerender.js:11499:1)
at webpack_require (angular-universal-starter/prerender.js:20:30)
at eval (webpack:///./node_modules/tooltip.js/dist/esm/tooltip.js?:2:67)
at Module../node_modules/tooltip.js/dist/esm/tooltip.js (angular-universal-starter/prerender.js:14088:1)
at webpack_require (angular-universal-starter/prerender.js:20:30)
at eval (webpack:///./node_modules/formiojs/components/_classes/component/Component.js?:58:39)
at Object../node_modules/formiojs/components/_classes/component/Component.js (angular-universal-starter/prerender.js:3936:1)
at webpack_require (angular-universal-starter/prerender.js:20:30)
at eval (webpack:///./node_modules/angular-material-formio/fesm5/angular-material-formio.js?:49:108)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! universal-demo@7.0.0 generate:prerender: node prerender.js
npm ERR! Exit status 1
