### ISSUE TITLE
1.8.4: Regression: window.PopperUtils

### ISSUE THREAD

**Issue by joscha** [FezVrasta/popper.js#241]
https://github.com/FezVrasta/popper.js/commit/f6c7e757e13727d260814ddede8baec2ccc5a7ad#diff-94e560edeef11a82815d4eeaff44e53cR344

broke any simple tool that involves loading popper, due to:

```
Popper.Utils = window.PopperUtils;
                     ^

TypeError: Cannot read property 'PopperUtils' of undefined
    at Object../node_modules/popper.js/dist/esm/popper.js (/Users/joscha/dev/canva/web/target/build/stories/stories.js:32963:22)
    at __webpack_require__ (/Users/joscha/dev/canva/web/target/build/stories/stories.js:20:30)
    at Object../src/ui/pin/pin.tsx (/Users/joscha/dev/canva/web/target/build/stories/stories.js:68216:14)
    at __webpack_require__ (/Users/joscha/dev/canva/web/target/build/stories/stories.js:20:30)
    at Object../src/ui/flyout/flyout.tsx (/Users/joscha/dev/canva/web/target/build/stories/stories.js:65476:13)
    at __webpack_require__ (/Users/joscha/dev/canva/web/target/build/stories/stories.js:20:30)
    at Object.<anonymous> (/Users/joscha/dev/canva/web/target/build/stories/stories.js:65533:16)
    at Object../src/ui/flyout/stories/flyout.stories.tsx (/Users/joscha/dev/canva/web/target/build/stories/stories.js:65546:30)
    at __webpack_require__ (/Users/joscha/dev/canva/web/target/build/stories/stories.js:20:30)
    at webpackContext (/Users/joscha/dev/canva/web/target/build/stories/stories.js:64267:9)
```

whereas before the import was resolved by node, now `window` is needed at import time.

This however only works for environments where `window` is available, which is not true for a lot of test runners and other node tools.

**Comment by joscha** [comment]
Thought I could work around by shimming `window` to `{}` in node, however there is a guard introduced via #166 that checks whether `window` is `undefined` - and if not accesses `navigator.userAgent`, so that needs to be filled as well...
