### ISSUE TITLE
build commands don't work in Windows shell

### ISSUE THREAD

**Issue by imkremen** [FezVrasta/popper.js#243]
I have next error when try "npm run build"

```
'$' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:524
    throw err;
    ^

Error: Command failed: $(npm bin)/gzipped ./dist//popper.js
'$' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at error (D:\Personal\Learn\popper.js\scripts\bundle.js:27:14)
    at ChildProcess.exithandler (child_process.js:195:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
[npm-debug.txt](https://github.com/FezVrasta/popper.js/files/957897/npm-debug.txt)

**Comment by FezVrasta** [comment]
What's your operative system?

**Comment by FezVrasta** [comment]
I don't think the build script can work on Windows. You should use the Bash on Windows shell or cygwin.

Alternatively, send a PR to make the command work on Windows as well.
