### ISSUE TITLE
popper.setAttribute is not a function

### ISSUE THREAD

**Issue by jonhue** [FezVrasta/popper.js#499]
### CodePen demo

https://codepen.io/anon/pen/PORKbZ

### What is the expected behavior?

Adding a popper to ref as done in [this pen](https://codepen.io/anon/pen/zPWdNJ)

### What went wrong?

```
Uncaught TypeError: popper.setAttribute is not a function
    at Object.applyStyleOnLoad [as onLoad] (https://unpkg.com/popper.js@1.12.9/dist/umd/popper.js:1142:10)
    at https://unpkg.com/popper.js@1.12.9/dist/umd/popper.js:2348:25
    at Array.forEach (<anonymous>)
    at new Popper (https://unpkg.com/popper.js@1.12.9/dist/umd/popper.js:2346:20)
    at pen.js:18:10
```

**Comment by FezVrasta** [comment]
This was a v0 API, please refer to the migration instructions:
https://github.com/FezVrasta/popper.js#migration-from-popperjs-v0
